spring: 
  datasource: 
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/orderfood
    username: root
    password: 123
    
  jpa: 
    hibernate:
      ddl-auto: create
    show-sql: true 
 
  thymeleaf:
    prefix: classpath:/templates/